# Generated by Django 5.1.7 on 2025-04-01 12:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.enums.project_roles
import core.enums.project_status


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CANCELLED", "Cancelled"),
                            ("DONE", "Done"),
                        ],
                        default=core.enums.project_status.ProjectStatus["PENDING"],
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_role",
                    models.CharField(
                        choices=[
                            ("READER", "Reader"),
                            ("MAINTAINER", "Maintainer"),
                            ("OWNER", "Owner"),
                        ],
                        default=core.enums.project_roles.ProjectRole["READER"],
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user"),
                ),
            ],
            options={
                "db_table": "user_project",
                "unique_together": {("user", "project")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(through="projects.UserProject", to="core.user"),
        ),
    ]
