# Generated by Django 5.1.7 on 2025-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CANCELLED", "Cancelled"),
                    ("DONE", "Done"),
                ],
                default="Pending",
            ),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="project_role",
            field=models.CharField(
                choices=[
                    ("READER", "Reader"),
                    ("MAINTAINER", "Maintainer"),
                    ("OWNER", "Owner"),
                ],
                default="Reader",
            ),
        ),
    ]
