# Generated by Django 5.1.7 on 2025-04-01 12:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.enums.task_roles
import core.enums.task_status


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CANCELLED", "Cancelled"),
                            ("DONE", "Done"),
                        ],
                        default=core.enums.task_status.TaskStatus["PENDING"],
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_role",
                    models.CharField(
                        choices=[
                            ("READER", "Reader"),
                            ("DEVELOPER", "Developer"),
                            ("OWNER", "Owner"),
                        ],
                        default=core.enums.task_roles.TaskRole["READER"],
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user"),
                ),
            ],
            options={
                "db_table": "user_task",
                "unique_together": {("user", "task")},
            },
        ),
    ]
