# Generated by Django 5.1.7 on 2025-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CANCELLED", "Cancelled"),
                    ("DONE", "Done"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="task_role",
            field=models.CharField(
                choices=[
                    ("READER", "Reader"),
                    ("DEVELOPER", "Developer"),
                    ("OWNER", "Owner"),
                ],
                default="Reader",
            ),
        ),
    ]
